collections_dir: blog
collections:
  minimal-devops:
    output: true
    permalink: /blog/:collection/:path
  monitoring:
    output: true
    permalink: /blog/:collection/:path
url: https://cronolio.ru
